# Generated by Django 3.1.14 on 2023-03-05 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0010_auto_20230305_1627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='last',
            new_name='lat',
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='appeared_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 5, 16, 30, 17, 154702), verbose_name='Время появления'),
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='disappeared_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 5, 16, 30, 17, 154702), verbose_name='Время исчезновения'),
        ),
    ]
